### ISSUE TITLE
Could not run with OpenJDK

### ISSUE THREAD

**Issue by StoyanDimitrov** [Jelmerro/F2Utility#1]
I use `java -jar F2Utility.jar` command to run the tool but it gives the following error:
```
Error: Could not find or load main class f2utility.F2Utility
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```
The output of `java -version` is
```
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
```

I can successfully run the [JOSM](https://josm.openstreetmap.de/) jar, for example, so I believe it is not the environment that is wrong.

**Comment by Jelmerro** [comment]
It seems to me you are missing JavaFX on your system.
You could try to install a package named `openjfx` on your system.
(See https://stackoverflow.com/questions/18547362/javafx-and-openjdk)

**Comment by StoyanDimitrov** [comment]
Installed the OpenJFX and successfully ran the [example code](https://github.com/openjfx/samples/tree/master/HelloFX/CLI) from the [installation page](https://openjfx.io/openjfx-docs/#install-javafx) but still can't run the jar with the same error.

**Comment by Jelmerro** [comment]
In that case, I don't think I'll be able to help with this problem.
As a last option, you could try building from source with Java 12 instead of 8 to see if that helps.

**Comment by StoyanDimitrov** [comment]
I used `jdeps --module-path "%PATH_TO_FX%" --print-module-deps F2Utility.jar` to list the required modules.

Then `java --module-path "%PATH_TO_FX%" --add-modules javafx.controls,javafx.swing -jar F2Utility.jar` was able to run the application.
