### ISSUE TITLE
can't launch using high sierra and openjdk 11

### ISSUE THREAD

**Issue by ndroftheline** [Jelmerro/F2Utility#2]
$ java -jar F2Utility\(1\).jar
Error: Could not find or load main class f2utility.F2Utility
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

thanks! this looks like a great project.

**Comment by Jelmerro** [comment]
Nowadays you need to install JavaFX separately using the steps listed here:
https://openjfx.io/openjfx-docs/#install-javafx
A similar issue was opened before, which includes some more background information: https://github.com/Jelmerro/F2Utility/issues/1 

After installing JavaFX, you can run F2Utility with a similar command as the one that StoyanDimitrov suggested:
`java --module-path $PATH_TO_FX --add-modules javafx.controls,javafx.swing -jar F2Utility.jar`
